version: '3.9'


services: 
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/hide-me
    
    ports:
      - 8005:8005
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:12.8
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  
volumes:
  postgres_data: